# This file is intended for use with Docker Hub automated builds testing:
# https://docs.docker.com/docker-hub/builds/automated-testing/

# TODO(dmu) LOW: Make this file DRY with `docker-compose.yml` or at least add linting for common parts being
#                exactly the same per character
version: '3.9'

services:

  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: core
      POSTGRES_USER: core
      POSTGRES_PASSWORD: core
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6-alpine
    volumes:
      - redis-data:/var/lib/redis

  sut:
    build: .
    environment:
      CORESETTING_DATABASES: '{"default":{"HOST":"db"}}'
      CORESETTING_CHANNEL_LAYERS: '{"default":{"CONFIG":{"hosts":[["redis", 6379]]}}}'
    command: make test-fail-fast
    depends_on:
      - db
      - redis

volumes:
  postgresql-data:
    driver: local
  redis-data:
    driver: local
