version: '3.9'

services:

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: core
      POSTGRES_USER: core
      POSTGRES_PASSWORD: core
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6-alpine
    volumes:
      - redis-data:/var/lib/redis

  core:
    image: ghcr.io/thenewboston-developers/core:latest
    restart: unless-stopped
    command: ./run.sh
    environment:
      CORESETTING_DATABASES: '{"default":{"HOST":"db"}}'
      CORESETTING_CHANNEL_LAYERS: '{"default":{"CONFIG":{"hosts":[["redis", 6379]]}}}'
    env_file: .env
    depends_on:
      - db
      - redis

  core-reverse-proxy:
    image: ghcr.io/thenewboston-developers/core-reverse-proxy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - core
    volumes:
      - letsencrypt:/etc/letsencrypt
      - acme-challenge:/usr/share/nginx/html/.well-known/acme-challenge/

  certbot:
    image: certbot/certbot:v1.26.0
    restart: unless-stopped
    entrypoint: /bin/sh
    # This will let us check certificate expiration every 7 days and renew if needed
    command: -c 'certbot renew; sleep 7d'
    volumes:
      - letsencrypt:/etc/letsencrypt
      - acme-challenge:/usr/share/nginx/html/.well-known/acme-challenge/

volumes:
  postgresql-data:
    driver: local
  redis-data:
    driver: local
  letsencrypt:
    driver: local
  acme-challenge:
    driver: local
