version: '3.9'

services:

  certbot:
    image: certbot/certbot:v1.26.0
    command: certificates
    ports:
      - 80:80
    volumes:
      - letsencrypt:/etc/letsencrypt

volumes:
  letsencrypt:
    driver: local
